"""Add Contabilidad and OC fields"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f0cc4f0840a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'movimientos', 'productos', ['producto_id'], ['id'], ondelete='SET NULL')
    op.add_column('ordenes_compra', sa.Column('tipo_compra', sa.String(length=50), nullable=True))
    op.add_column('ordenes_compra', sa.Column('canal_compra', sa.String(length=100), nullable=True))
    op.add_column('ordenes_compra', sa.Column('marca', sa.String(length=100), nullable=True))
    op.add_column('ordenes_compra', sa.Column('pago_msi', sa.Integer(), nullable=True))
    op.add_column('ordenes_compra', sa.Column('meses_msi', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_column('ordenes_compra', 'meses_msi')
    op.drop_column('ordenes_compra', 'pago_msi')
    op.drop_column('ordenes_compra', 'marca')
    op.drop_column('ordenes_compra', 'canal_compra')
    op.drop_column('ordenes_compra', 'tipo_compra')
    op.drop_constraint(None, 'movimientos', type_='foreignkey')
    # ### end Alembic commands ###
